[package]
name = "iota-macros"
version = "0.0.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
futures = "0.3"
once_cell = "1.21"
tracing = "0.1"

# internal dependencies
iota-proc-macros.workspace = true
