[package]
name = "iota-sdk-serde-derive"
version = "0.0.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2024"
license = "Apache-2.0"
publish = false
repository = "https://github.com/iotaledger/iota-rust-sdk/"
description = "A procedural macro to derive Serialize/Deserialize impls with a BCS/JSON split for IOTA SDK types"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
