enable-all-features = true
pre-release-hook = [
  "../../.github/gen_changelog.sh \"$CRATE_NAME\" \"$CRATE_ROOT\" \"$COMMIT_TO\" \"$NEW_VERSION\" true",
]
owners = ["github:iotaledger:dev-tools"]
sign-commit = true
