[package]
name = "iota-sdk-transaction-builder"
version = "0.0.1-alpha.1"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/iotaledger/iota-rust-sdk/"
description = "Transaction API for the IOTA Blockchain Rust SDK"

[features]
default = []
test-client = []

[lints]
workspace = true

[dependencies]
# external dependencies
base64ct = { workspace = true, features = ["std"] }
bcs.workspace = true
derive_more = { workspace = true, features = ["from"] }
primitive-types.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
variadics_please.workspace = true

# internal dependencies
iota-crypto = { workspace = true, features = ["ed25519", "secp256r1", "secp256k1"] }
iota-types = { workspace = true, features = ["serde", "hash"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[dev-dependencies]
# external dependencies
eyre.workspace = true
rand.workspace = true
serde_json.workspace = true

# internal dependencies
iota-types = { workspace = true, features = ["rand"] }
