name: "Start Local IOTA Network"
description: "Downloads and starts a local IOTA network for testing"

runs:
  using: "composite"
  steps:
    - name: Start PostgreSQL
      shell: bash
      run: |
        docker run -d \
        --name postgres \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_PASSWORD=postgrespw \
        -e POSTGRES_DB=iota_indexer_v2 \
        -e POSTGRES_HOST_AUTH_METHOD=trust \
        -p 5432:5432 \
        --health-cmd pg_isready \
        --health-interval 10s \
        --health-timeout 5s \
        --health-retries 5 \
        postgres

    - name: Get the IOTA alphanet binary and start a local network
      shell: bash
      env:
        IOTA_BINARY_VERSION: "v1.10.0-alpha"
        EPOCH_DURATION_MS: "10000"
      run: |
        ASSET_NAME="iota-$IOTA_BINARY_VERSION-linux-x86_64.tgz"
        download_url="https://github.com/iotaledger/iota/releases/download/$IOTA_BINARY_VERSION/$ASSET_NAME"

        echo "Downloading testnet binary from $download_url"
        wget -q $download_url -O iota.tgz
        tar -zxvf iota.tgz ./iota
        chmod +x ./iota
        echo "Starting local network with a faucet, an indexer (port 5432) and GraphQL. Epoch duration is set to $EPOCH_DURATION_MS ms"
        echo "$(pwd)" >> $GITHUB_PATH
        ./iota start --force-regenesis --with-faucet --with-indexer --with-graphql --pg-port 5432 --pg-db-name iota_indexer_v2 --epoch-duration-ms $EPOCH_DURATION_MS &
        sleep $((EPOCH_DURATION_MS / 1000)) # wait for the first epoch to end

    - name: Start gas station and request faucet coins
      shell: bash
      env:
        GAS_STATION_AUTH: "test"
      run: |
        ./iota client -y new-env --alias localnet --rpc http://127.0.0.1:9000 --graphql http://0.0.0.0:9125 --faucet http://127.0.0.1:9123/v1/gas
        ./iota keytool update-alias $(./iota client active-address) gas_station

        echo "Getting keypair"
        private_key="$(./iota keytool export gas_station --json | jq -r '.["exportedPrivateKey"]')"
        key="$(./iota keytool convert $private_key --json | jq -r '.["base64WithFlag"]')"

        echo "Setting keypair in config"
        sed -i "s|<keypair>|$key|g" ./.github/actions/start-local-network/config.yaml

        echo "Updating fullnode-url to use host IP"
        HOST_IP=$(hostname -I | awk '{print $1}')
        sed -i "s|http://localhost:9000|http://$HOST_IP:9000|g" ./.github/actions/start-local-network/config.yaml

        echo "Requesting faucet coins"
        ./iota client faucet --address gas_station

        echo "Starting Gas Station"
        docker compose -f ./.github/actions/start-local-network/gas_station_compose.yml up -d

        docker logs iota-gas-station & sleep 10
