// Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// Generated by uniffi-bindgen-react-native
// Allow clippy lints that are commonly triggered by the generated FFI module.
#![allow(clippy::too_many_arguments)]

#[cfg(target_arch = "wasm32")]
mod iota_sdk_ffi_module;

// end.
