name: "Python Pre-Publish"
description: "Python Pre-Publish steps"

inputs:
  level:
    description: "The level of the version bump"
    required: true

outputs:
  new-version:
    description: "The new version"
    value: ${{ steps.bump.outputs.next_version }}

runs:
  using: "composite"
  steps:
    - name: Bump release version and create changelog
      id: bump
      if: ${{ inputs.level == "alpha" || inputs.level == "beta" || inputs.level == "rc" }}
      uses: commitizen-tools/commitizen-action@master
      with:
        working-directory: "bindings/python/src"
        commitizen_version: "4.10.0"
        increment: ${{ inputs.level }}
        prerelease: true
        changelog: true
        changelog_increment_filename: "body.md"
        dry-run: true # TODO remove once tested

    - name: Release and create changelog
      id: bump
      if: ${{ inputs.level == "release" }}
      uses: commitizen-tools/commitizen-action@master
      with:
        working-directory: "bindings/python/src"
        commitizen_version: "4.10.0"
        prerelease: false
        changelog: true
        changelog_increment_filename: "body.md"
        dry-run: true # TODO remove once tested

    - name: Bump pre-release version and create changelog
      id: bump
      if: ${{ inputs.level == "major" || inputs.level == "minor" || inputs.level == "patch" }}
      uses: commitizen-tools/commitizen-action@master
      with:
        working-directory: "bindings/python/src"
        commitizen_version: "4.10.0"
        increment: ${{ inputs.level }}
        prerelease: false
        changelog: true
        changelog_increment_filename: "body.md"
        dry-run: true # TODO remove once tested
