name: Create incentivized task
description: Create a task for the SDK Incentivized Program.
title: "[Incentivized] "
labels:
  - "incentivized"

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the task and its goal.
      placeholder: "What should be done and why?"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated complexity
      description: >
        An easy task may require changing a few files, or adding some documentation.
        A medium difficulty task may require more knowledge of IOTA and the SDK, and may take as much as a day.
        A hard task could take multiple days and require a strong understanding of IOTA and the SDK.
      options:
        - Easy
        - Medium
        - Hard
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: Estimated duration
      description: >
        This should approximately correlate with the complexity.
      placeholder: "2 days"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details & acceptance criteria
      description: >
        Provide a clear description, scope, and acceptance criteria for this incentivized task.
      placeholder: |
        - Background / context
        - What is _in_ scope
        - What is explicitly _out_ of scope
        - Acceptance criteria (what must be true for the task to be considered done)
    validations:
      required: true

  - type: dropdown
    id: pr_required
    attributes:
      label: Pull request required?
      description: >
        Does this task require a code change via PR?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: markdown
    attributes:
      value: >
        ## Important

        - When submitting PRs to resolve incentivized issues, your commits should be signed in order to guarantee that the account can be verified.
