[build-system]
requires = ["maturin>=1.6,<2.0"]
build-backend = "maturin"

[project]
name = "iota-sdk"
version = "0.1.0"
description = "IOTA SDK Python bindings"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = ["cffi"]
authors = [{ name = "IOTA Foundation", email = "info@iota.org" }]

[project.urls]
homepage = "https://iota.org"

[tool.maturin]
bindings = "uniffi"
module-name = "iota_sdk"
manifest-path = "../../../crates/iota-sdk-ffi/Cargo.toml"
