// Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

//! Generates a module with constants for all known gRPC method paths.
//!
//! The output is a single file `service_methods.rs` that provides:
//! - A `&[&str]` constant per service listing its method paths.
//! - An `ALL_METHOD_PATHS` constant with every valid method path.
//!
//! These constants are derived from the proto service definitions, so they
//! update automatically when methods are added or removed.

use std::path::Path;

use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Generate a Rust source file containing constants for all gRPC method paths
/// discovered in the descriptor pool.
pub fn generate_service_method_paths(pool: &prost_reflect::DescriptorPool, out_dir: &Path) {
    let mut service_consts = Vec::new();
    let mut all_paths = Vec::new();

    for service in pool.services() {
        let service_full_name = service.full_name();

        // Skip google/protobuf built-in services
        if service_full_name.starts_with("google.") {
            continue;
        }

        let mut method_paths = Vec::new();
        for method in service.methods() {
            let path = format!("/{}/{}", service_full_name, method.name());
            method_paths.push(path);
        }

        if method_paths.is_empty() {
            continue;
        }

        // e.g. "iota.grpc.v1.ledger_service.LedgerService" -> "LEDGER_SERVICE"
        let const_name = service_const_name(service.name());
        let const_ident = format_ident!("{const_name}");

        let path_literals: Vec<TokenStream> = method_paths
            .iter()
            .map(|p| {
                let s = p.as_str();
                quote! { #s }
            })
            .collect();

        let count = method_paths.len();
        let doc = format!(" Known gRPC method paths for `{}`.", service.name());

        service_consts.push(quote! {
            #[doc = #doc]
            pub const #const_ident: [&str; #count] = [
                #( #path_literals ),*
            ];
        });

        all_paths.extend(method_paths);
    }

    let total = all_paths.len();
    let all_literals: Vec<TokenStream> = all_paths
        .iter()
        .map(|p| {
            let s = p.as_str();
            quote! { #s }
        })
        .collect();

    let tokens = quote! {
        #( #service_consts )*

        /// All known gRPC method paths across all services.
        pub const ALL_METHOD_PATHS: [&str; #total] = [
            #( #all_literals ),*
        ];
    };

    let code = prettyplease::unparse(&syn::parse2(tokens).unwrap());
    let output = format!(
        "// Copyright (c) 2026 IOTA Stiftung\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         \n\
         // Auto-generated gRPC method path constants.\n\
         // Generated by `iota-proto-build` from proto service definitions.\n\
         // Do not edit manually.\n\
         \n\
         {code}"
    );
    let out_file = out_dir.join("service_methods.rs");
    std::fs::write(out_file, output).unwrap();
}

/// Convert a service name like "LedgerService" to a constant name like
/// "LEDGER_SERVICE".
fn service_const_name(name: &str) -> String {
    name.to_snake_case().to_uppercase()
}
