// Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

//! Resolution of protobuf message types to their location in the generated
//! Rust module tree.
//!
//! Messages are keyed by their fully qualified protobuf name (the form
//! `FieldDescriptorProto::type_name` uses, e.g. `.iota.grpc.v1.command.
//! Argument.Input`), so that messages sharing a simple name stay distinct.

use std::collections::{BTreeMap, HashMap};

use proc_macro2::TokenStream;
use prost_types::DescriptorProto;
use quote::{format_ident, quote};

use crate::{codegen::generate_fields::FileDescriptorWithPackageVersion, ident::to_snake};

/// Where a protobuf message lives in the generated Rust module tree.
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct ResolvedType {
    /// Package declared by the file defining the message, e.g.
    /// `iota.grpc.v1.types`.
    package: String,
    /// Version module the package is generated under, e.g. `v1`.
    version: String,
    /// Names of the enclosing messages, outermost first. Empty for a top-level
    /// message.
    outer_messages: Vec<String>,
    /// Name of the message itself.
    name: String,
    /// Set for the synthetic entry messages backing a proto `map` field, which
    /// prost turns into a map instead of a type of its own.
    is_map_entry: bool,
}

impl ResolvedType {
    /// Path to the message type, as generated by prost.
    ///
    /// Messages of `from_package` that aren't nested are left unqualified: the
    /// generated file is included into that very module.
    pub(crate) fn message_path(&self, from_package: &str) -> TokenStream {
        let name = format_ident!("{}", self.name);

        if self.is_local_to(from_package) {
            return quote! { #name };
        }

        let root = self.package_path();
        let outer = self.outer_modules();
        quote! { #root #(::#outer)* ::#name }
    }

    /// Path to the field path builder generated for the message.
    pub(crate) fn builder_path(&self, from_package: &str) -> TokenStream {
        let builder = format_ident!("{}FieldPathBuilder", self.name);
        let outer = self.outer_modules();

        if self.package == from_package {
            // Builders are generated into `_field_impls` of the file being
            // written, mirroring the message nesting.
            return quote! { #(#outer::)* #builder };
        }

        let root = self.package_path();
        if self.outer_messages.is_empty() {
            quote! { #root::#builder }
        } else {
            // At the package root the nested module is shadowed by the prost
            // module of the same name, so the builder is only reachable
            // through `_field_impls`.
            quote! { #root::_field_impls #(::#outer)* ::#builder }
        }
    }

    pub(crate) fn is_map_entry(&self) -> bool {
        self.is_map_entry
    }

    fn is_local_to(&self, from_package: &str) -> bool {
        self.outer_messages.is_empty() && self.package == from_package
    }

    /// `crate::v1::types` for package `iota.grpc.v1.types`.
    fn package_path(&self) -> TokenStream {
        let version = format_ident!("{}", self.version);
        let package = format_ident!(
            "{}",
            self.package
                .split('.')
                .next_back()
                .unwrap_or(&self.package)
                .to_owned()
        );
        quote! { crate::#version::#package }
    }

    fn outer_modules(&self) -> Vec<proc_macro2::Ident> {
        self.outer_messages
            .iter()
            .map(|name| format_ident!("{}", to_snake(name)))
            .collect()
    }
}

/// All messages of all compiled packages, keyed by fully qualified protobuf
/// name.
#[derive(Debug, Default)]
pub(crate) struct TypeRegistry {
    types: HashMap<String, ResolvedType>,
}

impl TypeRegistry {
    pub(crate) fn new(packages: &BTreeMap<String, FileDescriptorWithPackageVersion>) -> Self {
        let mut registry = Self::default();

        for FileDescriptorWithPackageVersion { fd_set, version } in packages.values() {
            for file in &fd_set.file {
                // The package a message belongs to is the one its own file
                // declares, not the group it was collected under.
                let package = file.package().to_owned();
                registry.add_messages(&file.message_type, &package, version, &[]);
            }
        }

        registry
    }

    /// Resolves a fully qualified protobuf message name, panicking when it is
    /// unknown — every message type reachable from a field is compiled
    /// together with the field's own file.
    pub(crate) fn resolve(&self, full_type_name: &str) -> &ResolvedType {
        self.types
            .get(full_type_name)
            .unwrap_or_else(|| panic!("unknown protobuf message type {full_type_name}"))
    }

    fn add_messages(
        &mut self,
        messages: &[DescriptorProto],
        package: &str,
        version: &str,
        outer_messages: &[String],
    ) {
        for message in messages {
            let full_name = format!(
                ".{package}{}.{}",
                outer_messages
                    .iter()
                    .map(|outer| format!(".{outer}"))
                    .collect::<String>(),
                message.name()
            );

            self.types.insert(
                full_name,
                ResolvedType {
                    package: package.to_owned(),
                    version: version.to_owned(),
                    outer_messages: outer_messages.to_vec(),
                    name: message.name().to_owned(),
                    is_map_entry: message.options.as_ref().is_some_and(|o| o.map_entry()),
                },
            );

            let mut nested_outer = outer_messages.to_vec();
            nested_outer.push(message.name().to_owned());
            self.add_messages(&message.nested_type, package, version, &nested_outer);
        }
    }
}

#[cfg(test)]
mod tests {
    use prost_types::{FileDescriptorProto, FileDescriptorSet, MessageOptions};

    use super::*;

    fn message(name: &str, nested: Vec<DescriptorProto>) -> DescriptorProto {
        DescriptorProto {
            name: Some(name.to_owned()),
            nested_type: nested,
            ..Default::default()
        }
    }

    fn map_entry(name: &str) -> DescriptorProto {
        DescriptorProto {
            name: Some(name.to_owned()),
            options: Some(MessageOptions {
                map_entry: Some(true),
                ..Default::default()
            }),
            ..Default::default()
        }
    }

    fn registry() -> TypeRegistry {
        let mut packages = BTreeMap::new();

        for (package, version, messages) in [
            (
                "iota.grpc.v1.command",
                "v1",
                vec![
                    message("Argument", vec![message("Input", vec![])]),
                    message("Input", vec![]),
                ],
            ),
            (
                "iota.grpc.v1.types",
                "v1",
                vec![message(
                    "Input",
                    vec![message("Inner", vec![map_entry("EntriesEntry")])],
                )],
            ),
            ("iota.grpc.v2.types", "v2", vec![message("Input", vec![])]),
        ] {
            packages.insert(
                package.to_owned(),
                FileDescriptorWithPackageVersion {
                    fd_set: FileDescriptorSet {
                        file: vec![FileDescriptorProto {
                            name: Some(format!("{package}.proto")),
                            package: Some(package.to_owned()),
                            message_type: messages,
                            ..Default::default()
                        }],
                    },
                    version: version.to_owned(),
                },
            );
        }

        TypeRegistry::new(&packages)
    }

    fn message_path(full_type_name: &str, from_package: &str) -> String {
        registry()
            .resolve(full_type_name)
            .message_path(from_package)
            .to_string()
            .replace(' ', "")
    }

    fn builder_path(full_type_name: &str, from_package: &str) -> String {
        registry()
            .resolve(full_type_name)
            .builder_path(from_package)
            .to_string()
            .replace(' ', "")
    }

    #[test]
    fn same_name_in_different_packages_resolves_to_its_own_package() {
        assert_eq!(
            message_path(".iota.grpc.v1.types.Input", "iota.grpc.v1.command"),
            "crate::v1::types::Input"
        );
        assert_eq!(
            message_path(".iota.grpc.v2.types.Input", "iota.grpc.v1.command"),
            "crate::v2::types::Input"
        );
        assert_eq!(
            message_path(".iota.grpc.v1.command.Input", "iota.grpc.v1.types"),
            "crate::v1::command::Input"
        );
    }

    #[test]
    fn nested_messages_are_qualified_by_their_outer_messages() {
        assert_eq!(
            message_path(".iota.grpc.v1.command.Argument.Input", "iota.grpc.v1.types"),
            "crate::v1::command::argument::Input"
        );
        assert_eq!(
            message_path(".iota.grpc.v1.types.Input.Inner", "iota.grpc.v1.types"),
            "crate::v1::types::input::Inner"
        );
    }

    #[test]
    fn local_top_level_messages_are_unqualified() {
        assert_eq!(
            message_path(".iota.grpc.v1.command.Input", "iota.grpc.v1.command"),
            "Input"
        );
    }

    #[test]
    fn builders_of_the_same_package_are_relative_to_field_impls() {
        assert_eq!(
            builder_path(".iota.grpc.v1.command.Input", "iota.grpc.v1.command"),
            "InputFieldPathBuilder"
        );
        assert_eq!(
            builder_path(
                ".iota.grpc.v1.command.Argument.Input",
                "iota.grpc.v1.command"
            ),
            "argument::InputFieldPathBuilder"
        );
    }

    #[test]
    fn builders_of_other_packages_are_absolute() {
        assert_eq!(
            builder_path(".iota.grpc.v1.types.Input", "iota.grpc.v1.command"),
            "crate::v1::types::InputFieldPathBuilder"
        );
        assert_eq!(
            builder_path(".iota.grpc.v1.types.Input.Inner", "iota.grpc.v1.command"),
            "crate::v1::types::_field_impls::input::InnerFieldPathBuilder"
        );
    }

    #[test]
    fn map_entries_are_flagged() {
        assert!(
            registry()
                .resolve(".iota.grpc.v1.types.Input.Inner.EntriesEntry")
                .is_map_entry()
        );
        assert!(
            !registry()
                .resolve(".iota.grpc.v1.types.Input")
                .is_map_entry()
        );
    }
}
