[package]
name = "iota-sdk-ffi"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "iota_sdk_bindings"
path = "uniffi_bindgen.rs"

[lib]
name = "iota_sdk_ffi"
crate-type = ["lib", "cdylib"]

[dependencies]
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
derive_more = { version = "2.0", features = ["from", "deref"] }
rand = "0.8"
roaring = { version = "0.11.2", default-features = false }
serde_json = "1.0.95"
tokio = { version = "1.36.0", features = ["time"] }
uniffi = { version = "0.29", features = ["cli", "tokio"] }

iota-crypto = { path = "../iota-crypto", features = ["ed25519", "secp256r1", "passkey", "secp256k1", "zklogin", "pem"] }
iota-graphql-client = { path = "../iota-graphql-client" }
iota-transaction-builder = { path = "../iota-transaction-builder" }
iota-types = { package = "iota-sdk-types", path = "../iota-sdk-types", features = ["hash", "rand"] }
