[package]
name = "iota-transaction-builder"
version = "0.0.1"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
description = "Transaction API for the IOTA Blockchain Rust SDK"

[dependencies]
base64ct = { version = "1.6", features = ["std"] }
bcs = "0.1"
derive_more = { version = "2.0", features = ["from"] }
iota-crypto = { package = "iota-crypto", path = "../iota-crypto", features = ["ed25519"] }
iota-graphql-client = { package = "iota-graphql-client", path = "../iota-graphql-client" }
iota-types = { package = "iota-sdk-types", path = "../iota-sdk-types", features = ["serde", "hash"] }
primitive-types = { version = "0.14", features = ["impl-serde"] }
reqwest = "0.12"
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
variadics_please = "1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
tokio = { version = "1.0", features = ["macros", "rt"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
eyre = "0.6"
iota-types = { package = "iota-sdk-types", path = "../iota-sdk-types", features = ["rand"] }
rand = "0.8"
serde_json = "1.0"
