[package]
name = "iota-graphql-client"
version = "0.0.1"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/iotaledger/iota-rust-sdk/"
description = "GraphQL RPC Client for the IOTA Blockchain"

[dependencies]
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
bcs.workspace = true
chrono = "0.4.26"
cynic = "3.7.3"
derive_more = { version = "2.0", features = ["from"] }
eyre = "0.6"
futures = "0.3.29"
iota-types = { package = "iota-sdk-types", path = "../iota-sdk-types", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0.144" }
serde_json = { version = "1.0.95" }
strum = { version = "0.27.2", features = ["derive"] }
tokio = { version = "1.36.0", features = ["time"] }
tracing = "0.1.37"
url = "2.5.3"

[dev-dependencies]
hex = "0.4.3"
iota-crypto = { path = "../iota-crypto", features = ["ed25519", "pem", "bech32"] }
iota-transaction-builder = { path = "../iota-transaction-builder" }
iota-types = { package = "iota-sdk-types", path = "../iota-sdk-types", features = ["serde", "rand", "hash"] }
rand = "0.8.5"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
iota-graphql-client-build = { path = "../iota-graphql-client-build" }
