

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import asyncio
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_iota_graphql_client_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_iota_graphql_client_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_iota_graphql_client_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("iota_graphql_client")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 29
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_iota_graphql_client_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_iota_graphql_client_checksum_method_client_chain_id() != 24918:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_iota_graphql_client_checksum_constructor_client_new() != 30926:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_iota_graphql_client_checksum_constructor_client_new_devnet() != 1714:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_iota_graphql_client_checksum_constructor_client_new_localhost() != 60569:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_iota_graphql_client_checksum_constructor_client_new_mainnet() != 51011:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_iota_graphql_client_checksum_constructor_client_new_testnet() != 42249:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UniffiLib.uniffi_iota_graphql_client_fn_clone_client.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_clone_client.restype = ctypes.c_void_p
_UniffiLib.uniffi_iota_graphql_client_fn_free_client.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_free_client.restype = None
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new.restype = ctypes.c_void_p
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_devnet.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_devnet.restype = ctypes.c_void_p
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_localhost.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_localhost.restype = ctypes.c_void_p
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_mainnet.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_mainnet.restype = ctypes.c_void_p
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_testnet.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_testnet.restype = ctypes.c_void_p
_UniffiLib.uniffi_iota_graphql_client_fn_method_client_chain_id.argtypes = (
    ctypes.c_void_p,
)
_UniffiLib.uniffi_iota_graphql_client_fn_method_client_chain_id.restype = ctypes.c_uint64
_UniffiLib.uniffi_iota_graphql_client_fn_clone_error.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_clone_error.restype = ctypes.c_void_p
_UniffiLib.uniffi_iota_graphql_client_fn_free_error.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_iota_graphql_client_fn_free_error.restype = None
_UniffiLib.ffi_iota_graphql_client_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_iota_graphql_client_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_iota_graphql_client_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rustbuffer_free.restype = None
_UniffiLib.ffi_iota_graphql_client_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u8.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u8.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i8.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i8.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u16.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u16.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i16.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i16.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_u64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_u64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_i64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_i64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_f32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_f32.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_f64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_f64.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_pointer.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_poll_void.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_cancel_void.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_iota_graphql_client_rust_future_free_void.restype = None
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_iota_graphql_client_rust_future_complete_void.restype = None
_UniffiLib.uniffi_iota_graphql_client_checksum_method_client_chain_id.argtypes = (
)
_UniffiLib.uniffi_iota_graphql_client_checksum_method_client_chain_id.restype = ctypes.c_uint16
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new.argtypes = (
)
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_devnet.argtypes = (
)
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_devnet.restype = ctypes.c_uint16
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_localhost.argtypes = (
)
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_localhost.restype = ctypes.c_uint16
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_mainnet.argtypes = (
)
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_mainnet.restype = ctypes.c_uint16
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_testnet.argtypes = (
)
_UniffiLib.uniffi_iota_graphql_client_checksum_constructor_client_new_testnet.restype = ctypes.c_uint16
_UniffiLib.ffi_iota_graphql_client_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_iota_graphql_client_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.


class _UniffiConverterInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i32"
    VALUE_MIN = -2**31
    VALUE_MAX = 2**31

    @staticmethod
    def read(buf):
        return buf.read_i32()

    @staticmethod
    def write(value, buf):
        buf.write_i32(value)

class _UniffiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiConverterBool:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()






class ProtocolConfigAttr:
    """
    A key-value protocol configuration attribute.
    """

    key: "str"
    value: "typing.Optional[str]"
    def __init__(self, *, key: "str", value: "typing.Optional[str]"):
        self.key = key
        self.value = value

    def __str__(self):
        return "ProtocolConfigAttr(key={}, value={})".format(self.key, self.value)

    def __eq__(self, other):
        if self.key != other.key:
            return False
        if self.value != other.value:
            return False
        return True

class _UniffiConverterTypeProtocolConfigAttr(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ProtocolConfigAttr(
            key=_UniffiConverterString.read(buf),
            value=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.key)
        _UniffiConverterOptionalString.check_lower(value.value)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.key, buf)
        _UniffiConverterOptionalString.write(value.value, buf)


class ProtocolConfigFeatureFlag:
    """
    Feature flags are a form of boolean configuration that are usually used to
    gate features while they are in development. Once a lag has been enabled, it
    is rare for it to be disabled.
    """

    key: "str"
    value: "bool"
    def __init__(self, *, key: "str", value: "bool"):
        self.key = key
        self.value = value

    def __str__(self):
        return "ProtocolConfigFeatureFlag(key={}, value={})".format(self.key, self.value)

    def __eq__(self, other):
        if self.key != other.key:
            return False
        if self.value != other.value:
            return False
        return True

class _UniffiConverterTypeProtocolConfigFeatureFlag(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ProtocolConfigFeatureFlag(
            key=_UniffiConverterString.read(buf),
            value=_UniffiConverterBool.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.key)
        _UniffiConverterBool.check_lower(value.value)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.key, buf)
        _UniffiConverterBool.write(value.value, buf)


class ProtocolConfigs:
    """
    Information about the configuration of the protocol.
    Constants that control how the chain operates.
    These can only change during protocol upgrades which happen on epoch
    boundaries.
    """

    protocol_version: "int"
    """
    The protocol is not required to change on every epoch boundary, so the
    protocol version tracks which change to the protocol these configs
    are from.
    """

    feature_flags: "typing.List[ProtocolConfigFeatureFlag]"
    """
    List all available feature flags and their values. Feature flags are a
    form of boolean configuration that are usually used to gate features
    while they are in development. Once a flag has been enabled, it is
    rare for it to be disabled.
    """

    configs: "typing.List[ProtocolConfigAttr]"
    """
    List all available configurations and their values. These configurations
    can take any value (but they will all be represented in string
    form), and do not include feature flags.
    """

    def __init__(self, *, protocol_version: "int", feature_flags: "typing.List[ProtocolConfigFeatureFlag]", configs: "typing.List[ProtocolConfigAttr]"):
        self.protocol_version = protocol_version
        self.feature_flags = feature_flags
        self.configs = configs

    def __str__(self):
        return "ProtocolConfigs(protocol_version={}, feature_flags={}, configs={})".format(self.protocol_version, self.feature_flags, self.configs)

    def __eq__(self, other):
        if self.protocol_version != other.protocol_version:
            return False
        if self.feature_flags != other.feature_flags:
            return False
        if self.configs != other.configs:
            return False
        return True

class _UniffiConverterTypeProtocolConfigs(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ProtocolConfigs(
            protocol_version=_UniffiConverterUInt64.read(buf),
            feature_flags=_UniffiConverterSequenceTypeProtocolConfigFeatureFlag.read(buf),
            configs=_UniffiConverterSequenceTypeProtocolConfigAttr.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterUInt64.check_lower(value.protocol_version)
        _UniffiConverterSequenceTypeProtocolConfigFeatureFlag.check_lower(value.feature_flags)
        _UniffiConverterSequenceTypeProtocolConfigAttr.check_lower(value.configs)

    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt64.write(value.protocol_version, buf)
        _UniffiConverterSequenceTypeProtocolConfigFeatureFlag.write(value.feature_flags, buf)
        _UniffiConverterSequenceTypeProtocolConfigAttr.write(value.configs, buf)


class ServiceConfig:
    default_page_size: "int"
    """
    Default number of elements allowed on a single page of a connection.
    """

    enabled_features: "typing.List[Feature]"
    """
    List of all features that are enabled on this RPC service.
    """

    max_move_value_depth: "int"
    """
    Maximum estimated cost of a database query used to serve a GraphQL
    request.  This is measured in the same units that the database uses
    in EXPLAIN queries.
    Maximum nesting allowed in struct fields when calculating the layout of
    a single Move Type.
    """

    max_output_nodes: "int"
    """
    The maximum number of output nodes in a GraphQL response.
    Non-connection nodes have a count of 1, while connection nodes are
    counted as the specified 'first' or 'last' number of items, or the
    default_page_size as set by the server if those arguments are not
    set. Counts accumulate multiplicatively down the query tree. For
    example, if a query starts with a connection of first: 10 and has a
    field to a connection with last: 20, the count at the second level
    would be 200 nodes. This is then summed to the count of 10 nodes
    at the first level, for a total of 210 nodes.
    """

    max_page_size: "int"
    """
    Maximum number of elements allowed on a single page of a connection.
    """

    max_query_depth: "int"
    """
    The maximum depth a GraphQL query can be to be accepted by this service.
    """

    max_query_nodes: "int"
    """
    The maximum number of nodes (field names) the service will accept in a
    single query.
    """

    max_query_payload_size: "int"
    """
    Maximum length of a query payload string.
    """

    max_type_argument_depth: "int"
    """
    Maximum nesting allowed in type arguments in Move Types resolved by this
    service.
    """

    max_type_argument_width: "int"
    """
    Maximum number of type arguments passed into a generic instantiation of
    a Move Type resolved by this service.
    """

    max_type_nodes: "int"
    """
    Maximum number of structs that need to be processed when calculating the
    layout of a single Move Type.
    """

    mutation_timeout_ms: "int"
    """
    Maximum time in milliseconds spent waiting for a response from fullnode
    after issuing a a transaction to execute. Note that the transaction
    may still succeed even in the case of a timeout. Transactions are
    idempotent, so a transaction that times out should be resubmitted
    until the network returns a definite response (success or failure, not
    timeout).
    """

    request_timeout_ms: "int"
    """
    Maximum time in milliseconds that will be spent to serve one query
    request.
    """

    def __init__(self, *, default_page_size: "int", enabled_features: "typing.List[Feature]", max_move_value_depth: "int", max_output_nodes: "int", max_page_size: "int", max_query_depth: "int", max_query_nodes: "int", max_query_payload_size: "int", max_type_argument_depth: "int", max_type_argument_width: "int", max_type_nodes: "int", mutation_timeout_ms: "int", request_timeout_ms: "int"):
        self.default_page_size = default_page_size
        self.enabled_features = enabled_features
        self.max_move_value_depth = max_move_value_depth
        self.max_output_nodes = max_output_nodes
        self.max_page_size = max_page_size
        self.max_query_depth = max_query_depth
        self.max_query_nodes = max_query_nodes
        self.max_query_payload_size = max_query_payload_size
        self.max_type_argument_depth = max_type_argument_depth
        self.max_type_argument_width = max_type_argument_width
        self.max_type_nodes = max_type_nodes
        self.mutation_timeout_ms = mutation_timeout_ms
        self.request_timeout_ms = request_timeout_ms

    def __str__(self):
        return "ServiceConfig(default_page_size={}, enabled_features={}, max_move_value_depth={}, max_output_nodes={}, max_page_size={}, max_query_depth={}, max_query_nodes={}, max_query_payload_size={}, max_type_argument_depth={}, max_type_argument_width={}, max_type_nodes={}, mutation_timeout_ms={}, request_timeout_ms={})".format(self.default_page_size, self.enabled_features, self.max_move_value_depth, self.max_output_nodes, self.max_page_size, self.max_query_depth, self.max_query_nodes, self.max_query_payload_size, self.max_type_argument_depth, self.max_type_argument_width, self.max_type_nodes, self.mutation_timeout_ms, self.request_timeout_ms)

    def __eq__(self, other):
        if self.default_page_size != other.default_page_size:
            return False
        if self.enabled_features != other.enabled_features:
            return False
        if self.max_move_value_depth != other.max_move_value_depth:
            return False
        if self.max_output_nodes != other.max_output_nodes:
            return False
        if self.max_page_size != other.max_page_size:
            return False
        if self.max_query_depth != other.max_query_depth:
            return False
        if self.max_query_nodes != other.max_query_nodes:
            return False
        if self.max_query_payload_size != other.max_query_payload_size:
            return False
        if self.max_type_argument_depth != other.max_type_argument_depth:
            return False
        if self.max_type_argument_width != other.max_type_argument_width:
            return False
        if self.max_type_nodes != other.max_type_nodes:
            return False
        if self.mutation_timeout_ms != other.mutation_timeout_ms:
            return False
        if self.request_timeout_ms != other.request_timeout_ms:
            return False
        return True

class _UniffiConverterTypeServiceConfig(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ServiceConfig(
            default_page_size=_UniffiConverterInt32.read(buf),
            enabled_features=_UniffiConverterSequenceTypeFeature.read(buf),
            max_move_value_depth=_UniffiConverterInt32.read(buf),
            max_output_nodes=_UniffiConverterInt32.read(buf),
            max_page_size=_UniffiConverterInt32.read(buf),
            max_query_depth=_UniffiConverterInt32.read(buf),
            max_query_nodes=_UniffiConverterInt32.read(buf),
            max_query_payload_size=_UniffiConverterInt32.read(buf),
            max_type_argument_depth=_UniffiConverterInt32.read(buf),
            max_type_argument_width=_UniffiConverterInt32.read(buf),
            max_type_nodes=_UniffiConverterInt32.read(buf),
            mutation_timeout_ms=_UniffiConverterInt32.read(buf),
            request_timeout_ms=_UniffiConverterInt32.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterInt32.check_lower(value.default_page_size)
        _UniffiConverterSequenceTypeFeature.check_lower(value.enabled_features)
        _UniffiConverterInt32.check_lower(value.max_move_value_depth)
        _UniffiConverterInt32.check_lower(value.max_output_nodes)
        _UniffiConverterInt32.check_lower(value.max_page_size)
        _UniffiConverterInt32.check_lower(value.max_query_depth)
        _UniffiConverterInt32.check_lower(value.max_query_nodes)
        _UniffiConverterInt32.check_lower(value.max_query_payload_size)
        _UniffiConverterInt32.check_lower(value.max_type_argument_depth)
        _UniffiConverterInt32.check_lower(value.max_type_argument_width)
        _UniffiConverterInt32.check_lower(value.max_type_nodes)
        _UniffiConverterInt32.check_lower(value.mutation_timeout_ms)
        _UniffiConverterInt32.check_lower(value.request_timeout_ms)

    @staticmethod
    def write(value, buf):
        _UniffiConverterInt32.write(value.default_page_size, buf)
        _UniffiConverterSequenceTypeFeature.write(value.enabled_features, buf)
        _UniffiConverterInt32.write(value.max_move_value_depth, buf)
        _UniffiConverterInt32.write(value.max_output_nodes, buf)
        _UniffiConverterInt32.write(value.max_page_size, buf)
        _UniffiConverterInt32.write(value.max_query_depth, buf)
        _UniffiConverterInt32.write(value.max_query_nodes, buf)
        _UniffiConverterInt32.write(value.max_query_payload_size, buf)
        _UniffiConverterInt32.write(value.max_type_argument_depth, buf)
        _UniffiConverterInt32.write(value.max_type_argument_width, buf)
        _UniffiConverterInt32.write(value.max_type_nodes, buf)
        _UniffiConverterInt32.write(value.mutation_timeout_ms, buf)
        _UniffiConverterInt32.write(value.request_timeout_ms, buf)





class Feature(enum.Enum):
    ANALYTICS = 0
    
    COINS = 1
    
    DYNAMIC_FIELDS = 2
    
    NAME_SERVICE = 3
    
    SUBSCRIPTIONS = 4
    
    SYSTEM_STATE = 5
    
    MOVE_REGISTRY = 6
    


class _UniffiConverterTypeFeature(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Feature.ANALYTICS
        if variant == 2:
            return Feature.COINS
        if variant == 3:
            return Feature.DYNAMIC_FIELDS
        if variant == 4:
            return Feature.NAME_SERVICE
        if variant == 5:
            return Feature.SUBSCRIPTIONS
        if variant == 6:
            return Feature.SYSTEM_STATE
        if variant == 7:
            return Feature.MOVE_REGISTRY
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Feature.ANALYTICS:
            return
        if value == Feature.COINS:
            return
        if value == Feature.DYNAMIC_FIELDS:
            return
        if value == Feature.NAME_SERVICE:
            return
        if value == Feature.SUBSCRIPTIONS:
            return
        if value == Feature.SYSTEM_STATE:
            return
        if value == Feature.MOVE_REGISTRY:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Feature.ANALYTICS:
            buf.write_i32(1)
        if value == Feature.COINS:
            buf.write_i32(2)
        if value == Feature.DYNAMIC_FIELDS:
            buf.write_i32(3)
        if value == Feature.NAME_SERVICE:
            buf.write_i32(4)
        if value == Feature.SUBSCRIPTIONS:
            buf.write_i32(5)
        if value == Feature.SYSTEM_STATE:
            buf.write_i32(6)
        if value == Feature.MOVE_REGISTRY:
            buf.write_i32(7)





class _UniffiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterSequenceTypeProtocolConfigAttr(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeProtocolConfigAttr.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeProtocolConfigAttr.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeProtocolConfigAttr.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeProtocolConfigFeatureFlag(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeProtocolConfigFeatureFlag.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeProtocolConfigFeatureFlag.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeProtocolConfigFeatureFlag.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeFeature(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeFeature.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeFeature.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeFeature.read(buf) for i in range(count)
        ]

# objects.
class ClientProtocol(typing.Protocol):
    """
    The GraphQL client for interacting with the IOTA blockchain.
    By default, it uses the `reqwest` crate as the HTTP client.
    """

    def chain_id(self, ):
        """
        Get the chain identifier.
        """

        raise NotImplementedError
# Client is a Rust-only trait - it's a wrapper around a Rust implementation.
class Client():
    """
    The GraphQL client for interacting with the IOTA blockchain.
    By default, it uses the `reqwest` crate as the HTTP client.
    """

    _pointer: ctypes.c_void_p
    def __init__(self, server: "str"):
        """
        Create a new GraphQL client with the provided server address.
        """

        _UniffiConverterString.check_lower(server)
        
        self._pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeError__as_error,_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new,
        _UniffiConverterString.lower(server))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_free_client, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_clone_client, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst
    @classmethod
    def new_devnet(cls, ):
        """
        Create a new GraphQL client connected to the `devnet` GraphQL server:
        {DEVNET_HOST}.
        """

        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_devnet,)
        return cls._make_instance_(pointer)

    @classmethod
    def new_localhost(cls, ):
        """
        Create a new GraphQL client connected to the `localhost` GraphQL server:
        {DEFAULT_LOCAL_HOST}.
        """

        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_localhost,)
        return cls._make_instance_(pointer)

    @classmethod
    def new_mainnet(cls, ):
        """
        Create a new GraphQL client connected to the `mainnet` GraphQL server:
        {MAINNET_HOST}.
        """

        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_mainnet,)
        return cls._make_instance_(pointer)

    @classmethod
    def new_testnet(cls, ):
        """
        Create a new GraphQL client connected to the `testnet` GraphQL server:
        {TESTNET_HOST}.
        """

        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_constructor_client_new_testnet,)
        return cls._make_instance_(pointer)


    async def chain_id(self, ) -> "str":
        """
        Get the chain identifier.
        """

        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_iota_graphql_client_fn_method_client_chain_id(
                self._uniffi_clone_pointer(), 
            ),
            _UniffiLib.ffi_iota_graphql_client_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_iota_graphql_client_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_iota_graphql_client_rust_future_free_rust_buffer,
            # lift function
            _UniffiConverterString.lift,
            
    # Error FFI converter
_UniffiConverterTypeError__as_error,

        )





class _UniffiConverterTypeClient:

    @staticmethod
    def lift(value: int):
        return Client._make_instance_(value)

    @staticmethod
    def check_lower(value: Client):
        if not isinstance(value, Client):
            raise TypeError("Expected Client instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: ClientProtocol):
        if not isinstance(value, Client):
            raise TypeError("Expected Client instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: ClientProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))
class ErrorProtocol(typing.Protocol):
    """
    General error type for the client. It is used to wrap all the possible
    errors that can occur.
    """

    pass
# Error is a Rust-only trait - it's a wrapper around a Rust implementation.
class Error(Exception):
    """
    General error type for the client. It is used to wrap all the possible
    errors that can occur.
    """

    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_free_error, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_iota_graphql_client_fn_clone_error, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst



class _UniffiConverterTypeError__as_error(_UniffiConverterRustBuffer):
    @classmethod
    def read(cls, buf):
        raise NotImplementedError()

    @classmethod
    def write(cls, value, buf):
        raise NotImplementedError()

    @staticmethod
    def lift(value):
        # Errors are always a rust buffer holding a pointer - which is a "read"
        with value.consume_with_stream() as stream:
            return _UniffiConverterTypeError.read(stream)

    @staticmethod
    def lower(value):
        raise NotImplementedError()

class _UniffiConverterTypeError:

    @staticmethod
    def lift(value: int):
        return Error._make_instance_(value)

    @staticmethod
    def check_lower(value: Error):
        if not isinstance(value, Error):
            raise TypeError("Expected Error instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: ErrorProtocol):
        if not isinstance(value, Error):
            raise TypeError("Expected Error instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: ErrorProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

# Async support# RustFuturePoll values
_UNIFFI_RUST_FUTURE_POLL_READY = 0
_UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1

# Stores futures for _uniffi_continuation_callback
_UniffiContinuationHandleMap = _UniffiHandleMap()

_UNIFFI_GLOBAL_EVENT_LOOP = None

"""
Set the event loop to use for async functions

This is needed if some async functions run outside of the eventloop, for example:
    - A non-eventloop thread is spawned, maybe from `EventLoop.run_in_executor` or maybe from the
      Rust code spawning its own thread.
    - The Rust code calls an async callback method from a sync callback function, using something
      like `pollster` to block on the async call.

In this case, we need an event loop to run the Python async function, but there's no eventloop set
for the thread.  Use `uniffi_set_event_loop` to force an eventloop to be used in this case.
"""
def uniffi_set_event_loop(eventloop: asyncio.BaseEventLoop):
    global _UNIFFI_GLOBAL_EVENT_LOOP
    _UNIFFI_GLOBAL_EVENT_LOOP = eventloop

def _uniffi_get_event_loop():
    if _UNIFFI_GLOBAL_EVENT_LOOP is not None:
        return _UNIFFI_GLOBAL_EVENT_LOOP
    else:
        return asyncio.get_running_loop()

# Continuation callback for async functions
# lift the return value or error and resolve the future, causing the async function to resume.
@_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK
def _uniffi_continuation_callback(future_ptr, poll_code):
    (eventloop, future) = _UniffiContinuationHandleMap.remove(future_ptr)
    eventloop.call_soon_threadsafe(_uniffi_set_future_result, future, poll_code)

def _uniffi_set_future_result(future, poll_code):
    if not future.cancelled():
        future.set_result(poll_code)

async def _uniffi_rust_call_async(rust_future, ffi_poll, ffi_complete, ffi_free, lift_func, error_ffi_converter):
    try:
        eventloop = _uniffi_get_event_loop()

        # Loop and poll until we see a _UNIFFI_RUST_FUTURE_POLL_READY value
        while True:
            future = eventloop.create_future()
            ffi_poll(
                rust_future,
                _uniffi_continuation_callback,
                _UniffiContinuationHandleMap.insert((eventloop, future)),
            )
            poll_code = await future
            if poll_code == _UNIFFI_RUST_FUTURE_POLL_READY:
                break

        return lift_func(
            _uniffi_rust_call_with_error(error_ffi_converter, ffi_complete, rust_future)
        )
    finally:
        ffi_free(rust_future)

__all__ = [
    "InternalError",
    "Feature",
    "ProtocolConfigAttr",
    "ProtocolConfigFeatureFlag",
    "ProtocolConfigs",
    "ServiceConfig",
    "Client",
    "Error",
]

