export * from './iota_sdk_ffi';
import * as iota_sdk_ffi from './iota_sdk_ffi';
// Import the JS glue from wasm-bindgen (--target bundler).
// The __wbg_set_wasm function wires WASM exports into the JS glue.
import * as bg from './wasm-bindgen/index_bg.js';
// JS glue generated by `wasm-bindgen --target web` for the FFI implementation WASM.
// Provides wbg.* helper imports (e.g. getrandom JS bindings) that
// iota_sdk_ffi_bg.wasm requires at instantiation time.
// @ts-ignore - no TypeScript declarations (generated with --no-typescript)
import initFfi from './wasm-bindgen-ffi/iota_sdk_ffi.js';

/**
 * Load and initialise the WASM modules.
 *
 * Architecture – two-WASM shared-table dynamic linking:
 *
 *   index_bg.wasm      – wasm-bindgen wrapper; built with --export-table
 *                        --growable-table so its __indirect_function_table
 *                        can be grown and shared.  Has ~40 table entries
 *                        (continuation callbacks, vtable stubs, …).
 *
 *   iota_sdk_ffi_bg.wasm – actual Rust implementation; built with
 *                        --import-table so it imports the shared table
 *                        instead of declaring its own.  Its ~1900 functions
 *                        are placed at tableBase+ in the shared table.
 *
 * Why this matters
 * ----------------
 * uniffi-core's scheduler calls the continuation callback via a plain Rust
 * function pointer, which in WASM compiles to call_indirect(N).  N is a
 * table index from index_bg.wasm's table (the `implementation` function in
 * the rust_future_continuation_callback module).  Without a shared table,
 * iota_sdk_ffi_bg.wasm's call_indirect(N) looks up N in its OWN table and
 * finds a completely different function → RuntimeError / silent wrong call.
 *
 * With --import-table, iota_sdk_ffi_bg.wasm uses the shared table for every
 * call_indirect, so:
 *   N  < tableBase  →  index_bg.wasm callbacks (implementation, vtable fns)
 *   N >= tableBase  →  ffi module's own internal functions
 *
 * Both resolve correctly.
 *
 * Initialisation sequence
 * -----------------------
 * Phase 1 – Instantiate index_bg.wasm with a lazy env proxy.
 *   All env.* calls (uniffi_iota_sdk_ffi_fn_*) are deferred until Phase 3.
 *   No env functions are called during WASM instantiation itself (the
 *   wasm-bindgen start function is invoked manually in Phase 3).
 *
 * Phase 2 – Grow the shared table, then instantiate iota_sdk_ffi_bg.wasm.
 *   We temporarily monkeypatch WebAssembly.instantiate to inject the
 *   env.{__indirect_function_table, __table_base} imports that --import-table
 *   requires.  initFfi() handles the wbg.* imports (getrandom, etc.).
 *
 * Phase 3 – Wire the proxy to real ffi exports, run start, initialize.
 *
 * @param wasmUrl - URL to index_bg.wasm.  Defaults to import.meta.url-relative.
 */
export async function uniffiInitAsync(wasmUrl?: string | URL): Promise<void> {
  // ─── Phase 1: Instantiate index_bg.wasm with a lazy env proxy ─────────────
  //
  // The proxy captures every env.* function import at instantiation time and
  // forwards calls to the real ffi export once it is available (Phase 3).
  // This breaks the circular dependency:
  //   index_bg.wasm needs ffi exports  →  ffi module needs index_bg.wasm's table
  //   (we resolve the table dependency first, then wire up the functions).

  const envTarget: Record<string, (...args: unknown[]) => unknown> = {};
  const envProxy = new Proxy(envTarget, {
    get(target, name: string) {
      // Return a closure that defers to the real function at call time.
      return (...args: unknown[]): unknown => {
        const fn = target[name];
        if (typeof fn === 'function') return fn(...args);
        throw new Error(
          `env.${name} was called before the FFI module was wired up. ` +
            'This indicates the WASM start function ran before Phase 3.',
        );
      };
    },
  });

  const indexUrl = wasmUrl ?? new URL('./index_bg.wasm', import.meta.url);
  const indexBytes = await fetch(indexUrl).then((r) => r.arrayBuffer());

  // Instantiate index_bg.wasm.  No env functions are called here; the
  // wasm-bindgen start is invoked manually at the end of Phase 3.
  const { instance: indexInstance } = await WebAssembly.instantiate(
    indexBytes,
    { './index_bg.js': bg as any, env: envProxy as any },
  );

  // ─── Phase 2: Grow the shared table, instantiate iota_sdk_ffi_bg.wasm ─────
  //
  // index_bg.wasm was built with --export-table --growable-table and
  // wasm-bindgen was invoked with --keep-lld-exports, so the
  // __indirect_function_table is preserved as an export.

  const bgTable = (indexInstance.exports as any)
    .__indirect_function_table as WebAssembly.Table | undefined;

  if (!bgTable) {
    throw new Error(
      'index_bg.wasm did not export __indirect_function_table.\n' +
        'Ensure it is built with -C link-arg=--export-table and that ' +
        'wasm-bindgen is invoked with --keep-lld-exports ' +
        '(wasmBindgenExtras in ubrn.config.yaml).',
    );
  }

  // tableBase is where ffi module functions will start in the shared table.
  const tableBase = bgTable.length; // e.g. 40

  // Grow generously: iota_sdk_ffi_bg.wasm has ~1900 function-table entries.
  // Extra null slots are harmless; running out causes an instantiation trap.
  bgTable.grow(2048);

  // iota_sdk_ffi_bg.wasm was built with --import-table.  It imports:
  //   env.__indirect_function_table  (table)
  //   env.__table_base               (i32 global)
  // The generated iota_sdk_ffi.js only adds wbg.* to the imports object, so
  // we temporarily monkeypatch WebAssembly.instantiate to inject env.*.
  //
  // We pass ffiBytes explicitly (not a URL/Response) so that wasm-bindgen's
  // init function takes the non-streaming code path and calls
  // WebAssembly.instantiate(buffer, imports) – exactly what we intercept.
  const ffiWasmUrl = new URL(
    './wasm-bindgen-ffi/iota_sdk_ffi_bg.wasm',
    import.meta.url,
  );
  const ffiBytes = await fetch(ffiWasmUrl).then((r) => r.arrayBuffer());

  const tableBaseGlobal = new WebAssembly.Global(
    { value: 'i32', mutable: false },
    tableBase,
  );

  const origInstantiate = WebAssembly.instantiate;
  (WebAssembly as any).instantiate = async (
    bytes: any,
    importObject: any,
    ...rest: any[]
  ): Promise<any> => {
    // Inject the shared-table env imports required by --import-table.
    // Extra keys in importObject are silently ignored by the WASM runtime,
    // so this is safe even if the module has no env imports (e.g. if the
    // binary was built without --import-table for some reason).
    if (importObject) {
      importObject['env'] = {
        __indirect_function_table: bgTable,
        __table_base: tableBaseGlobal,
      };
    }
    return origInstantiate.call(WebAssembly, bytes, importObject, ...rest);
  };

  let ffiExports: Record<string, unknown>;
  try {
    // initFfi() handles wbg.* imports (getrandom crypto bindings, etc.),
    // compiles + instantiates iota_sdk_ffi_bg.wasm, sets the internal `wasm`
    // variable, and returns instance.exports.
    //
    // During instantiation, the ffi module's elem segments run and write
    // function references into bgTable[tableBase .. tableBase+N].
    ffiExports = (await (initFfi as any)(ffiBytes)) as Record<
      string,
      unknown
    >;
  } finally {
    // Always restore the original, even if initFfi throws.
    (WebAssembly as any).instantiate = origInstantiate;
  }

  // After instantiation:
  //   bgTable[0 .. tableBase-1]       = index_bg.wasm callbacks
  //   bgTable[tableBase .. tableBase+N] = iota_sdk_ffi_bg.wasm functions
  //
  // call_indirect(N) in iota_sdk_ffi_bg.wasm now resolves both correctly.

  // ─── Phase 3: Wire proxy, complete initialisation ─────────────────────────

  // Fill the backing store so every deferred env call reaches the real ffi fn.
  Object.assign(envTarget, ffiExports);

  // Hand the WASM instance exports to the wasm-bindgen JS glue.
  (bg as any).__wbg_set_wasm(indexInstance.exports);

  // Run the wasm-bindgen start function (sets up panic hook, etc.).
  if (typeof (indexInstance.exports as any).__wbindgen_start === 'function') {
    (indexInstance.exports as any).__wbindgen_start();
  }

  // Initialise the uniffi SDK layer (registers callback vtables etc.).
  iota_sdk_ffi.default.initialize();
}

export default { iota_sdk_ffi };
