export * from './iota_sdk_ffi';
import * as iota_sdk_ffi from './iota_sdk_ffi';
// Import the JS glue from wasm-bindgen (--target bundler).
// The __wbg_set_wasm function wires WASM exports into the JS glue.
import * as bg from './wasm-bindgen/index_bg.js';
// JS glue generated by `wasm-bindgen --target web` for the FFI implementation WASM.
// Provides the 'env' import module (uniffi_iota_sdk_ffi_fn_* / ffi_iota_sdk_ffi_*)
// that index_bg.wasm requires at instantiation time.
// @ts-ignore - no TypeScript declarations (generated with --no-typescript)
import initFfi from './wasm-bindgen-ffi/iota_sdk_ffi.js';

/**
 * Load and initialise the WASM modules.
 *
 * This performs two-step WASM initialisation required by the ubrn
 * dynamic-linking architecture:
 *   1. iota_sdk_ffi_bg.wasm – the actual Rust implementation; exports
 *      uniffi_iota_sdk_ffi_fn_* and ffi_iota_sdk_ffi_* symbols.
 *   2. index_bg.wasm – the thin wasm-bindgen wrapper; imports those
 *      symbols from the 'env' module provided by step 1.
 *
 * @param wasmUrl - URL to index_bg.wasm.  Resolved from import.meta.url when omitted.
 */
export async function uniffiInitAsync(wasmUrl?: string | URL) {
  // Step 1: initialise the FFI WASM (actual Rust implementation).
  // initFfi returns instance.exports which contains all uniffi_iota_sdk_ffi_fn_*
  // and ffi_iota_sdk_ffi_* functions; these satisfy index_bg.wasm's 'env' imports.
  const ffiExports = await (initFfi as any)();

  // Step 2: initialise the wasm-bindgen wrapper WASM using the FFI exports as 'env'.
  const url = wasmUrl ?? new URL('./index_bg.wasm', import.meta.url);
  const response = await fetch(url);
  const bytes = await response.arrayBuffer();

  const { instance } = await WebAssembly.instantiate(bytes, {
    './index_bg.js': bg as any,
    'env': ffiExports,
  });

  (bg as any).__wbg_set_wasm(instance.exports);
  if (typeof (instance.exports as any).__wbindgen_start === 'function') {
    (instance.exports as any).__wbindgen_start();
  }
  iota_sdk_ffi.default.initialize();
}

export default { iota_sdk_ffi };
