<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS0659</NoWarn>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>IotaSdk</PackageId>
    <PackageVersion>1.0.0-alpha</PackageVersion>
    <Authors>IOTA Foundation</Authors>
    <Description>C# bindings for the IOTA SDK</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/iotaledger/iota-rust-sdk</PackageProjectUrl>
    <RepositoryUrl>https://github.com/iotaledger/iota-rust-sdk</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>iota;sdk;blockchain;csharp;dotnet</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="libiota_sdk_ffi.*">
      <Pack>true</Pack>
      <PackagePath>runtimes/any/native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\runtimes\**\*" Condition="Exists('..\..\runtimes')">
      <Pack>true</Pack>
      <PackagePath>runtimes</PackagePath>
    </None>
  </ItemGroup>

</Project>
