[package]
name = "async-compat"
version = "0.2.5"
edition = "2024"
license = "Apache-2.0 OR MIT"
publish = false
description = "Compatibility adapter between tokio and futures (patched for wasm32)"

[dependencies]
pin-project-lite = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt"] }
