name: Bindings

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: bindings-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  diff:
    if: (!github.event.pull_request.draft || contains(github.event.pull_request.body, '[run-ci]'))
    runs-on: ubuntu-latest
    outputs:
      isBindings: ${{ steps.diff.outputs.isBindings }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Detect Changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: diff
        with:
          filters: |
            isBindings:
              - ".github/workflows/bindings.yml"
              - "bindings/**"
              - "crates/iota-sdk-ffi/**"

  go:
    if: (!cancelled() && needs.diff.outputs.isBindings == 'true')
    needs: diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install uniffi-bindgen-go
        run: cargo install uniffi-bindgen-go --git https://github.com/filament-dm/uniffi-bindgen-go --rev ab7315502bd6b979207fdae854e87d531ee8764d
      - name: Build the bindings
        run: make go
      - name: Checks for uncommitted changes
        run: git diff --exit-code
      - name: Check format of the examples
        run: make go-examples-format-check
      - uses: ./.github/actions/start-local-network
      - name: Run the examples
        run: make go-examples
      - name: Run the release example
        run: make go-release-example

  kotlin:
    if: (!cancelled() && needs.diff.outputs.isBindings == 'true')
    needs: diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build the bindings
        run: make kotlin
      - name: Checks for uncommitted changes
        run: git diff --exit-code
      - uses: actions/setup-java@v5
        with:
          distribution: "oracle"
          java-version: "21"
      - name: Check format of the examples
        run: make kotlin-examples-format-check
      - uses: ./.github/actions/start-local-network
      - name: Run the examples
        run: make kotlin-examples
      - name: Run the release example
        run: make kotlin-release-example

  python:
    if: (!cancelled() && needs.diff.outputs.isBindings == 'true')
    needs: diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build the bindings
        run: make python
      - name: Checks for uncommitted changes
        run: git diff --exit-code
      - name: Check format of the examples
        run: |
          pip install yapf
          make python-examples-format-check
      - uses: ./.github/actions/start-local-network
      - name: Run the examples
        run: make python-examples
      - name: Run the release example
        run: make python-release-example

  swift:
    if: (!cancelled() && needs.diff.outputs.isBindings == 'true')
    needs: diff
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build the bindings
        run: make swift
