name: Bindings

on:
  push:
    branches: [develop]
    paths:
      - ".github/workflow/bindings.yml"
      - "bindings/**"
      - "crates/iota-sdk-ffi/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: bindings-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  go:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer_v2
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install uniffi-bindgen-go
        run: cargo install uniffi-bindgen-go --git https://github.com/filament-dm/uniffi-bindgen-go --rev ab7315502bd6b979207fdae854e87d531ee8764d
      - name: Build the bindings
        run: make go
      - name: Checks for uncommitted changes
        run: git diff --exit-code
      - uses: ./.github/actions/start-local-network
      - name: Run the examples
        run: make go-examples
  kotlin:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer_v2
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build the bindings
        run: make kotlin
      - name: Checks for uncommitted changes
        run: git diff --exit-code
      - uses: actions/setup-java@v5
        with:
          distribution: "oracle"
          java-version: "21"
      - uses: ./.github/actions/start-local-network
      - name: Run the examples
        run: make kotlin-examples
  python:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer_v2
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build the bindings
        run: make python
      - name: Checks for uncommitted changes
        run: git diff --exit-code
      - name: Check format of the examples
        run: |
          pip install yapf
          make python-examples-format-check
      - uses: ./.github/actions/start-local-network
      - name: Run the examples
        run: make python-examples
