name: Feature Compatibility

on:
  schedule:
    - cron: "0 1 * * *" # every day at 1am (UTC)
  workflow_dispatch:
    inputs:
      branch-or-commit:
        description: "Branch or commit to run feature compatibility checks."
        type: string
        required: false
        default: ""

concurrency:
  group: check-features-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  check-features:
    name: Feature compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.branch-or-commit || github.ref }}

      - uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # v2.86.3
        with:
          tool: cargo-hack

      - name: Check feature compatibility
        run: make check-features
