name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@cargo-nextest

      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@cargo-hack

      - name: Install latest nightly
        run: rustup toolchain install nightly --component rustfmt --allow-downgrade

      - name: feature compatibility
        run: make check-features

      - name: rustfmt
        run: cargo +nightly fmt -- --check

      - name: clippy
        run: make clippy

      - name: rustdoc
        run: make doc

  wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@wasm-pack

      - name: Install clang
        run: sudo apt-get install -y clang

      - name: Run tests in wasm
        run: make wasm
