name: Lints

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

concurrency:
  group: dprint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check dprint formatting
        run: dprint check
