name: Publish Go SDK to iotaledger/iota-sdk-go

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version of iota-sdk-go to publish"
        required: true
        type: string

jobs:
  prepare-source-archive:
    name: Prepare source archive
    if: (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'iota-go-sdk')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout iota-rust-sdk
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: go-source

      - name: Install uniffi-bindgen-go
        run: make install-uniffi-bindgen-go

      - name: Generate Go bindings
        run: make go

      - name: Archive Go SDK source
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: source
          path: |
            bindings/go/iota_sdk
            bindings/go/README.md

  prepare-libraries-archives:
    name: Prepare libraries archives
    if: (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'iota-go-sdk')) || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            lib: libiota_sdk_ffi.dylib
            folder: darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            lib: libiota_sdk_ffi.dylib
            folder: darwin-aarch64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            lib: libiota_sdk_ffi.so
            folder: linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            lib: libiota_sdk_ffi.so
            folder: linux-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            lib: iota_sdk_ffi.dll
            folder: windows-amd64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            lib: iota_sdk_ffi.dll
            folder: windows-aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout iota-rust-sdk
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Install rust target ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}

      - name: Install gcc-aarch64-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: go-${{ matrix.target }}

      - name: Build ${{ matrix.os }} ${{ matrix.target }} library
        if: matrix.os == 'macos-latest'
        run: RUSTFLAGS="-C link-args=-Wl,-install_name,@rpath/${{ matrix.lib }}" cargo build -p iota-sdk-ffi --lib --release --target ${{ matrix.target }}

      - name: Build ${{ matrix.os }} ${{ matrix.target }} library
        if: matrix.os == 'ubuntu-latest'
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: /usr/bin/aarch64-linux-gnu-gcc
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: /usr/bin/x86_64-linux-gnu-gcc
        run: RUSTFLAGS="-C link-args=-Wl,-rpath,$ORIGIN" cargo build -p iota-sdk-ffi --lib --release --target ${{ matrix.target }}

      - name: Build ${{ matrix.os }} ${{ matrix.target }} library
        if: matrix.os == 'windows-latest'
        run: cargo build -p iota-sdk-ffi --lib --release --target ${{ matrix.target }}

      - name: Prepare library archive
        run: |
          mkdir -p tmp/lib/${{ matrix.folder }}
          cp target/${{ matrix.target }}/release/${{ matrix.lib }} tmp/lib/${{ matrix.folder }}/${{ matrix.lib }}

      - name: Archive ${{ matrix.target }} library
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ matrix.target }}
          path: tmp

  release-archives:
    name: Release archives
    runs-on: ubuntu-latest
    needs:
      - prepare-source-archive
      - prepare-libraries-archives
    steps:
      - name: Checkout iota-sdk-go
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          repository: iotaledger/iota-sdk-go
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_GO_SDK }}
          fetch-depth: 0

      - name: Download source and libraries archives
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          merge-multiple: true

      - name: Set version to input or release tag
        id: set-version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            version="${{ inputs.version }}"
          else
            version=$(echo "${{ github.event.release.tag_name }}" | sed -nr 's|iota-go-sdk-v(.*)|\1|p')
          fi
          version="${version#v}" # Remove leading 'v' if present
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Tag the Go SDK
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git add .
          git commit -m "Update Go SDK to version v${{ steps.set-version.outputs.version }}"
          git push
          git tag v${{ steps.set-version.outputs.version }} -m "v${{ steps.set-version.outputs.version }}"
          git push --tags
