name: License check

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: license-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  license-check:
    runs-on: self-hosted-x64
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: cargo license-template --template .license_template --ignore .license_ignore
