name: Publish to PyPi

on:
  # TODO: remove after testing
  push:
    branches: [ci/python-release]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (leave empty for release version)"
        required: false
        type: string
      dry_run:
        description: "Dry run - publish to Test-PyPi repo only"
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            lib_ext: so
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            lib_ext: so
          - os: macos-latest
            target: x86_64-apple-darwin
            lib_ext: dylib
          - os: macos-latest
            target: aarch64-apple-darwin
            lib_ext: dylib
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            lib_ext: dll
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Upload native library
        uses: actions/upload-artifact@v4
        with:
          name: native-lib-${{ matrix.os }}-${{ matrix.target }}
          path: bindings/python/lib/*iota_sdk_ffi*
