name: Release

on:
  push:
    tags:
      - "*-v*.*.*-alpha.*"
      - "*-v*.*.*-beta.*"
      - "*-v*.*.*-rc.*"
      - "*-v*.*.*"

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Show the tag
        run: |
          echo "tag is: ${{ github.ref_name }}"

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pkg=$(echo "${{github.ref_name}}" | sed -nr 's|(.*)-v.*|\1|p'
          gh release create ${{ github.ref_name }} --verify-tag --title ${{ github.ref_name }} --draft --notes-file $pkg/CHANGELOG.md
