name: Create release

on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
        description: The package to publish.
      version:
        type: string
        required: true
        description: The exact version.
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        description: The package to publish.
        options:
          - iota-sdk-types
          - iota-sdk-crypto
          - iota-sdk-graphql-client-build
          - iota-sdk-graphql-client
          - iota-sdk-transaction-builder
          - iota-sdk
      version:
        type: string
        description: The exact version.
  pull_request:
    types: closed
    branches: [develop]

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  create-release:
    if: github.event.pull_request == null || (github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set package and tag from inputs
        if: github.event.pull_request == null
        run: |
          echo "TAG=${{ inputs.package }}-v${{ inputs.version }}" >> $GITHUB_ENV
          echo "PKG=${{ inputs.package }}" >> $GITHUB_ENV
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Set package and tag from ref
        if: github.event.pull_request.merged == true
        run: |
          tag=$(echo "${{ github.head_ref }}" | sed -nr 's|release/(.*)/(.*)|\1-v\2|p')
          pkg=$(echo "${{ github.head_ref }}" | sed -nr 's|release/(.*)/.*|\1|p')
          version=$(echo "${{ github.head_ref }}" | sed -nr 's|release/.*/(.*)|\1|p')
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "PKG=$pkg" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV

      # TODO why is it taking the whole changelog file?
      # TODO handle bindings changelog
      # TODO bring back notes "--notes-file "crates/$PKG/CHANGELOG.md"
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.TAG }}
          PKG: ${{ env.PKG }}
          VERSION: ${{ env.VERSION }}
        run: |
          if [[ "$VERSION" =~ .*-alpha\..*  ]] || [[ "$VERSION" =~ .*-beta\..*  ]] || [[ "$VERSION" =~ .*-rc\..*  ]]; then
            gh release create "$TAG" --title "$TAG" --target ${{ github.sha }} --draft --prerelease
          else
            gh release create "$TAG" --title "$TAG" --target ${{ github.sha }} --draft
          fi
