name: Publish Rust SDK to crates.io

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish ${{github.event.release.tag_name}} to crates.io
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'iota-sdk')
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install cargo-release
        uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # v2.86.3
        with:
          tool: cargo-release@0.25.20

      - name: Cargo release publish
        run: |
          pkg=$(echo "${{github.event.release.tag_name}}" | sed -nr 's|(.*)-v.*|\1|p')
          version=$(echo "${{github.event.release.tag_name}}" | sed -nr 's|.*-v(.*)|\1|p')

          cargo login ${{ secrets.CRATES_IO_TOKEN }}

          echo "Publishing $pkg at version $version"
          cargo release publish -p "$pkg" --all-features --allow-branch "*" --no-confirm --execute

          echo "Setting owners of $pkg"
          cargo release owner -p "$pkg" --allow-branch "*" --no-confirm --execute
