name: Tests

on:
  push:
    branches: [develop, sdk-bindings]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

concurrency:
  group: tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@cargo-nextest

      - name: Run tests
        run: make test

  tests-with-network:
    runs-on: ubuntu-latest
    services:
      postgres: # we need this postgres instance for running a local network with indexer and graphql
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer_v2
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@cargo-nextest

      - uses: ./.github/actions/start-local-network

      - name: Run tests that require local network (GraphQL Client and Tx Builder)
        env:
          NETWORK: "local"
        run: make test-with-localnet

  doctests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: doctests
        run: |
          cargo test --doc
      - name: rustdoc
        run: |
          cargo doc --all-features --workspace --no-deps
