name: Tests

on:
  push:
    branches: [develop, sdk-bindings]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

concurrency:
  group: tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@cargo-nextest

      - name: Run tests
        run: make test

  tests-with-network:
    runs-on: ubuntu-latest
    env:
      EPOCH_DURATION_MS: 10000
    services:
      postgres: # we need this postgres instance for running a local network with indexer and graphql
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer_v2
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@cargo-nextest

      - name: Get the IOTA testnet binary and start a local network
        shell: bash
        env:
          IOTA_BINARY_VERSION: "v0.12.0-rc" # used for downloading a specific IOTA binary version that matches the GraphQL schema for local network tests
        run: |
          ASSET_NAME="iota-$IOTA_BINARY_VERSION-linux-x86_64.tgz"
          download_url="https://github.com/iotaledger/iota/releases/download/$IOTA_BINARY_VERSION/$ASSET_NAME"

          echo "Downloading testnet binary from $download_url"
          wget -q $download_url -O iota.tgz
          tar -zxvf iota.tgz ./iota
          chmod +x ./iota
          echo "Starting local network with a faucet, an indexer (port 5432) and GraphQL. Epoch duration is set to $EPOCH_DURATION_MS ms"
          echo "$(pwd)" >> $GITHUB_PATH # we need it on the path for calling iota move build for some tests
          ./iota start --force-regenesis --with-faucet --with-indexer --with-graphql --pg-port 5432 --pg-db-name iota_indexer_v2 --epoch-duration-ms $EPOCH_DURATION_MS &

      - name: Run tests that require local network (GraphQL Client and Tx Builder)
        env:
          NETWORK: "local" # other expected options are mainnet, testnet, or devnet, or an actual URL to a GraphQL server: http://localhost:port
        run: |
          sleep $((EPOCH_DURATION_MS / 1000)) # wait for the network to get to epoch #2
          make test-with-localnet

  doctests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: doctests
        run: |
          cargo test --doc
      - name: rustdoc
        run: |
          cargo doc --all-features --workspace --no-deps
