name: Tests

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

concurrency:
  group: tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  tests:
    if: (!github.event.pull_request.draft || contains(github.event.pull_request.body, '[run-ci]'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # v2.86.3
        with:
          tool: cargo-nextest

      - name: Run tests
        run: make test

  tests-with-network:
    if: (!github.event.pull_request.draft || contains(github.event.pull_request.body, '[run-ci]'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: rust version
        run: |
          rustc --version
          cargo --version

      - uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # v2.86.3
        with:
          tool: cargo-nextest

      - uses: ./.github/actions/start-local-network

      - name: Run tests that require local network (GraphQL Client and Tx Builder)
        env:
          NETWORK: "local"
        run: make test-with-localnet

  examples:
    if: (!github.event.pull_request.draft || contains(github.event.pull_request.body, '[run-ci]'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/start-local-network

      - name: Run the examples
        run: make examples

      - name: Run the release example
        run: make rust-release-example

      - name: Run the polling-indexer example
        run: |
          docker exec postgres psql -U postgres -c "CREATE DATABASE polling_indexer;"
          cargo run -p polling-indexer -- \
            --graphql-url http://localhost:9125/graphql \
            --db-url postgres://postgres:postgrespw@localhost:5432/polling_indexer \
            --start-checkpoint 0 \
            --end-checkpoint 5

  doctests:
    if: (!github.event.pull_request.draft || contains(github.event.pull_request.body, '[run-ci]'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: doctests
        run: |
          make test-docs
      - name: rustdoc
        run: |
          make build-docs
